# Generated by Django 4.1.7 on 2023-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_worker_description_alter_worker_phone_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='description',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='phone',
        ),
        migrations.AddField(
            model_name='work',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='numberOfWorker',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='role',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='startDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
