# Generated by Django 4.1.7 on 2023-04-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_work_description_remove_worker_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='numberOfWorker',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='worker',
            name='rating',
            field=models.FloatField(blank=True, default=3.7, null=True),
        ),
    ]
