# Generated by Django 4.1.7 on 2023-04-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_work_currentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='currentStatus',
        ),
    ]
