# Generated by Django 4.1.7 on 2023-04-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_work_currentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
