# Generated by Django 4.1.7 on 2023-04-04 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_work_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='startDateTime',
        ),
        migrations.AddField(
            model_name='work',
            name='startDate',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
        ),
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_assigned',
            field=models.ManyToManyField(blank=True, to='base.work'),
        ),
    ]
