# Generated by Django 4.1.7 on 2023-04-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_worker_work_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='status',
        ),
        migrations.AddField(
            model_name='worker',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
