# Generated by Django 4.1.7 on 2023-04-08 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_worker_status_worker_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='assignee',
            field=models.ManyToManyField(blank=True, to='base.worker'),
        ),
        migrations.AlterField(
            model_name='work',
            name='startDate',
            field=models.DateField(default=datetime.date(2023, 4, 8)),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=300, null=True),
        ),
    ]
