# Generated by Django 4.1.7 on 2023-04-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_work_assignee_alter_work_startdate_alter_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.work'),
        ),
    ]
