# Generated by Django 4.1.7 on 2023-04-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_worker_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='assigned',
        ),
        migrations.AddField(
            model_name='worker',
            name='assigned',
            field=models.ManyToManyField(blank=True, to='base.work'),
        ),
    ]
